name: azure-deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  AZURE_FUNCTIONAPP_NAME: 'fnsb20221012'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '${{ github.workspace }}/GitHubActionsApp'
  BUILD_OUTPUT_PATH: '${{ github.workspace }}/build-artifacts'
  BUILD_PACKAGE_NAME: 'az-func.zip'    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: 'Build and package code'
      shell: bash
      run: |
        publishfolder="${{ github.workspace }}/output"
        mkdir $publishfolder
        cd $publishfolder
        dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output .
        mkdir ${{ env.BUILD_OUTPUT_PATH }}
        zip -r ${{ env.BUILD_OUTPUT_PATH }}/${{ env.BUILD_PACKAGE_NAME }} .
        
    - name: 'Package Azure Function release build'
      uses: actions/upload-artifact@v2
      with:
        name: build_artifacts
        path: ${{ env.BUILD_OUTPUT_PATH }}
        if-no-files-found: error        

  deploy-az-function:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: 'Fetching Azure Functions Publishing Profile'
        id: fncapp
        uses: azure/powershell@v1
        with:
          inlineScript: |
              $profile = ""
              $profile = Get-AzWebAppSlotPublishingProfile -ResourceGroupName github-actions  -Name fnsb20221012 -Slot prelive
              $profile = $profile.Replace("`r", "").Replace("`n", "")
              Write-Output "::set-output name=pubprofile::$profile"
              Remove-Variable profile
          azPSVersion: "latest"
          
      - name: 'Download Azure function release build'
        uses: actions/download-artifact@v2
        with:
          name: build_artifacts
          path: ${{ env.BUILD_OUTPUT_PATH }}

      - name: 'Run Azure Functions Action'
        uses: azure/functions-action@v1
        with:
           app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
           package: ${{ env.BUILD_OUTPUT_PATH }}/${{ env.BUILD_PACKAGE_NAME }}
           publish-profile: ${{ steps.fncapp.outputs.pubprofile }} 
           slot-name: prelive
  
