name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  DOTNET_VERSION: '3.1.x'
  AZURE_FUNCTIONAPP_NAME: 'greetingservice'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '${{ github.workspace }}/src/GreetingDemo.Function'
  BUILD_OUTPUT_PATH: '${{ github.workspace }}/build-artifacts'
  BUILD_PACKAGE_NAME: 'az-func.zip'    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: 'Build and package code'
      shell: bash
      run: |
        publishfolder="${{ github.workspace }}/output"
        mkdir $publishfolder
        cd $publishfolder
        dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output .
        mkdir ${{ env.BUILD_OUTPUT_PATH }}
        zip -r ${{ env.BUILD_OUTPUT_PATH }}/${{ env.BUILD_PACKAGE_NAME }} .
  	 
   	# Upload the code artifact, this will be used later
    - name: 'Package Azure Function release build'
      uses: actions/upload-artifact@v2
      with:
        name: build_artifacts
        path: ${{ env.BUILD_OUTPUT_PATH }}
        if-no-files-found: error
        
#     - name: Login to Azure
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
#         enable-AzPSSession: true
        
#     - name: 'Fetching Azure Functions Publishing Profile'
#       id: fncapp
#       uses: azure/powershell@v1
#       with:
#         inlineScript: |
#             $profile = ""
#             $profile = Get-AzWebAppPublishingProfile -ResourceGroupName github-actions  -Name fnsb20221012
#             $profile = $profile.Replace("`r", "").Replace("`n", "")
#             Write-Output "::set-output name=pubprofile::$profile"
#             Remove-Variable profile
#         azPSVersion: "latest"        
